config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  
  resources :orders, only: [:index, :show, :create, :destroy]

  get 'static_pages/about'

  get 'static_pages/contact'
  post 'static_pages/thank_you'

  get 'static_pages/index'

  root 'static_pages#index'

     resources :products do
       resources :comments
      end
     resources :users

end

app/views/shared/_carousel.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
	<%  loadedProducts = @products.all %>
	<!-- Indicators -->
	<ol class="carousel-indicators">
		<% for i in 0..loadedProducts.length-1 %>
		<li data-target="#carousel-example-generic" data-slide-to="<% i %>" class="<% "active" if i == 0 %>">
		</li>
	 <% end %>
	</ol>
	 
	<!--Wrapper for slides -->
	<div class="carousel-inner" role="listbox">
		<% @products.each do |product| %>
		<div class="item<%= " active" if product == @products.last %>">
			<%= image_tag(product.image_url) %>
			<div class="carousel-caption">
				<%= product.name %>
			</div>	
		</div>
		<% end %>
	</div>	
		

<!-- Controls -->
<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
	<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
	<span class="sr-only">Previous</span>
</a>
<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
	<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
	<span class="sr-only">Next</span>
</a>
</div>

app/views/shared/_introduction.html.erb
<%= image_tag("NMstateflag.jpg", class: "img-responsive content") %>
<h2>One taste will take you to the Land of Enchantment</h2>
<br>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid" id="navbar">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav" id="nav-buttons1">
        <li><%= link_to "Home", static_pages_index_path %></li>
        <li><%= link_to "About", static_pages_about_path %></li>
        <li><%= link_to "Contact", static_pages_contact_path %></li>
      
        <li><%= link_to "Orders", orders_path %></li>
        <li class="<%= "active" if params[:controller] == "products" %>"><%= link_to "Products", products_path %></li>
      <!-- Search Form -->
      <li><%= form_tag("/products", method: "get", class: "navbar-form navbar-left") do %>
        <div class="form-group">
          <%= text_field_tag(:q, nil, class: "form-control", placeholder: "Search") %>
        </div>
          <%= submit_tag("Search", class: "btn btn-default") %>
      <% end %>
    </li>
     <li>
      <% if user_signed_in? %>
        <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
      <% else %>
        <%= link_to('Login', new_user_session_path) %>
      <% end %>
    </li>
  </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_stripe_checkout_button.html.erb
<script
	src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
 
  data-name="<%= @product.name %>"
  data-description="<%= @product.description %> "
  data-amount="<%= @product.price * 100 %>">
</script>