config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  
  resources :orders, only: [:index, :show, :create, :destroy]

  get 'static_pages/about'

  get 'static_pages/contact'
  post 'static_pages/thank_you'

  get 'static_pages/index'

  root 'static_pages#index'

     resources :products do
       resources :comments
      end
     resources :users

end

app/models/product.rb
class Product < ActiveRecord::Base
has_many :orders
has_many :comments
validates :name, presence: true
	
	def average_rating
		comments.average(:rating).to_f
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  respond_to :json, :html
  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.where("LOWER(name) LIKE ? OR LOWER(description) LIKE?", "%#{search_term.downcase}%", 
      "%#{search_term.downcase}")
    else
      @products = Product.all
    end
    respond_with @products
  end


  # GET /products/1
  # GET /products/1.json
  def show
   @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_path }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
	<% @comments.each do |comment| %>
		<div class="row">
			<hr>
			<p><% comment.user.first_name %>
				<small><em><%= "#{time_ago_in_words(comment.created_at)} ago:" %></em></small>
				<% if signed_in? && current_user.admin? %>	
				<%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
				<% end %>
			</p>
			<p><%= comment.body %></p>
			<br>
			<p>Rating: <div class="rated" id="rated" data-score="<%= comment.rating %>">
	 		</div>
	 	 </div>
	 <% end %>
  </div>
  

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-4", id="form-fields">
      <div class="field">
        <%= f.label :name, :class => "form-label" %><br>
        <%= f.text_field :name, :class => "form-control", :type => "text" %>
      </div>
      <div class="field">
        <%= f.label :description, :class => "form-label" %><br>
        <%= f.text_area :description, :class => "form-control", :id => "textbox", :type => "text" %>
      </div>
      <div class="field">
        <%= f.label :image_url, :class => "form-label" %><br>
        <%= f.text_field :image_url, :class => "form-control", :type => "text" %>
      </div>
      <div class="field">
        <%= f.label :colour, :class => "form-label" %><br>
        <%= f.text_field :colour, :class => "form-control", :type => "text" %>
      </div>
      <div class="field">
        <%= f.label :price, :class => "form-label" %><br>
        <%= f.text_field :price, :class => "form-control", :type => "number" %>
      </div>
        <div class="actions">
          <%= f.submit %>
        </div>
        <% end %>
    </div>
  </div>
 

app/views/products/_new_comment.html.erb
<% if signed_in? %>
	<div class="new-review">
	<h4>Add a review:</h4>
		<%= form_for([@product, @product.comments.build], remote: true) do |f| %>
		<p>
			<%= f.label :body, "Comments" %><br>
			<%= f.text_area :body %>
		</p>
		<p>
			<div class="rating"></div> 
		</p>
		<br>	
		<p>
			<%= f.submit "Submit" %>
		</p>
	<% end %>
 </div>	
<% end %>

app/views/products/_product.html.erb
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
   <div class="row">
    <div style="height: 450px">
      <div class="boxed">
       <% cache product do %>
        <%= link_to image_tag(product.image_url, class: "img-responsive", id:"pic1"), product %>
        <% end %>
        <h2><%= link_to product.name, product %></h2>
        <p><%= product.description %></p>
        <p><%= product.colour %></p>
        <p><strong> $ <%=product.price %></strong></p>
      
     </div>  
    </div>
  </div>     
</div>


     

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render partial: 'form'%>
    
<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Current Products</h2>

<h2> We only sell the freshest peppers grown in New Mexico</h2>
<br>
<div class="container-fluid">
  <div class="row">
    <% cache(cache_key_for_products) do %>
      <%= render @products %> 
    <% end %>
  </div>
</div>
<!-- <table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Colour</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.image_url %></td>
        <td><%= product.colour %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
-->
<br>

<div class="new-product"><%= link_to 'New Product', new_product_path %></div>
<br>

app/views/products/new.html.erb
<h1>New Product</h1>

	<%= render partial: 'form'%>
		
<div id="back-button">
<%= link_to 'Back', products_path %>
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container", id="display">
  <div class="row">
    <div class="col-sm-4 col-md-8 col-lg-8">
      <% cache @product do %>
        <h4><strong>
          <%= @product.name %>
        </strong></h4>
     <br>
      <%= image_tag(@product.image_url, id:"pic2", class: "img-zoom", data_zoom_image:@product.image_url) %>
     <br>
      <p>
        <strong class="glyphicon glyphicon-minus"></strong>Description:
          <%= @product.description %>
      </p>

      <p>
         <strong class="glyphicon glyphicon-minus"></strong>Colour:
           <%= @product.colour %>
      </p>
      <p>
       <strong class="glyphicon glyphicon-minus"></strong>Price: $
         <%= @product.price %>
      </p>
      <br>
      <p>Average Rating: <div class="rated" data-score="<%= @product.average_rating %>"></div></p>
      <br>
      <div class="container" id="payments">
      <%= form_tag "/payments/create" do %>
      <%= hidden_field_tag(:product_id, @product.id) %>
      <%= render partial: "shared/stripe_checkout_button" %>
      <% end %>
    </div> 
    <br>
    <% end %>
  <div class="review">
    <%= render partial: 'new_comment' %>

    <%= render partial: 'comments' %>
  </div>
  <br>
    </div>
  </div>
    <div class="pagination" id="pagination">  
      <h5><%= will_paginate @comments %></h5>
    </div>
    <br>
    <div id="links">
      <%= link_to 'Edit', edit_product_path(@product) %> |
      <%= link_to 'Back', products_path %>
    </div> 
</div>